// src/renderer/components/SyncInfo/SyncInfo.vue
<template>
  <div
    style="padding: .75rem"
    class="h-full w-full overflow-y-auto overflow-x-hidden"
  >
    <!-- <div class="flex items-center justify-between mb-3">
      <p class="text-gray-500 text-sm sticky top-0 bg-gray-50"></p>
      <p class="text-gray-500 font-bold text-xs cursor-pointer" @click="clear">
        Clear
      </p>
    </div> -->
    <div class="flex flex-col space-y-4 ">
      <div
        v-for="item in items"
        :key="item.name"
        class="flex items-center w-full"
      >
        <file-icon-with-operation
          :operation="getOperation(item)"
          size="32"
          class="flex-shrink-0 flex-grow-0"
        />
        <div class="ml-2 flex-shrink flex-grow min-w-0">
          <p class="text-sm truncate mt-1">
            {{ item.name | showOnlyFilename }}
          </p>
          <p class="text-xs text-gray-600">{{ getStatusMessage(item) }}</p>
        </div>
        <UilInfoCircle
          v-if="isAnError(item)"
          size="20px"
          class=" text-blue-500 cursor-pointer hover:opacity-60 flex-shrink-0 flex-grow-0"
          @click.native="openSyncIssuesWindow"
        />
      </div>
    </div>
    <div
      v-if="items.length === 0"
      class="h-full flex flex-col items-center justify-center text-center"
    >
      <div class="relative w-full h-20">
        <div
          class="absolute transform rotate-12 left-1/2 -translate-x-6 opacity-60"
        >
          <file-icon-with-operation :size="70" />
        </div>
        <div class="absolute transform -rotate-12 left-1/2 -translate-x-10">
          <file-icon-with-operation :size="70" />
        </div>
      </div>
      <p class="mt-7 text-sm text-gray-600">There is no recent activity</p>
      <p class="mt-1 text-xs text-gray-400 px-4">
        Information will show up here when changes are made to sync your local
        folder with Internxt Drive
      </p>
    </div>
  </div>
</template>

<script>
import { UilFolder, UilCloud, UilInfoCircle } from '@iconscout/vue-unicons'
import path from 'path'
import FileIconWithOperation from '../Icons/FileIconWithOperation.vue'
import { shortMessages } from '../../../sync/sync-error-messages'
import { ipcRenderer } from 'electron'
import syncStatus from '../../../sync/sync-status'
const app = require('@electron/remote').app

export default {
  components: {
    UilFolder,
    UilCloud,
    UilInfoCircle,
    FileIconWithOperation
  },
  data() {
    return {
      items: []
    }
  },
  mounted() {
    app.on('SYNC_INFO_UPDATE', this.onInfoUpdate)
    app.on('sync-status-changed', this.onSyncStatusChanged)
    app.on('SYNC_NEXT', this.onNext)
  },
  beforeDestroy() {
    app.removeListener('SYNC_INFO_UPDATE', this.onInfoUpdate)
    app.removeListener('sync-status-changed', this.onSyncStatusChanged)
    app.removeListener('SYNC_NEXT', this.onNext)
  },
  methods: {
    onInfoUpdate(item) {
      if (
        ![
          'PULL',
          'DELETE',
          'PULLED',
          'DELETED',
          'PULL_ERROR',
          'DELETE_ERROR',
          'METADATA_READ_ERROR'
        ].includes(item.action)
      ) {
        return
      }

      const itemIndex = this.items.findIndex(i => i.name === item.name)

      const alreadyExists = itemIndex !== -1

      if (!alreadyExists) {
        this.items = [item, ...this.items.slice(0, 50)]
      } else {
        const itemsCopy = [...this.items]
        itemsCopy[itemIndex] = item
        this.items = itemsCopy
      }
    },
    onSyncStatusChanged(newStatus) {
      if (newStatus === syncStatus.RUNNING) this.items = []
    },
    onNext() {
      this.items = this.items.filter(item => item.progress === undefined)
    },
    clear() {},
    getStatusMessage(item) {
      if (item.action === 'PULL' && item.kind === 'REMOTE') {
        return `Uploading (${(item.progress * 100).toFixed(0)}%)`
      } else if (item.action === 'PULL' && item.kind === 'LOCAL') {
        return `Downloading (${(item.progress * 100).toFixed(0)}%)`
      }
      if (item.action === 'PULLED' && item.kind === 'REMOTE') {
        return `Uploaded`
      } else if (item.action === 'PULLED' && item.kind === 'LOCAL') {
        return `Downloaded`
      } else if (item.action === 'PULL_ERROR') {
        return shortMessages[item.errorName]
      } else if (item.action === 'DELETE' && item.kind === 'LOCAL') {
        return `Deleting from your computer`
      } else if (item.action === 'DELETE' && item.kind === 'REMOTE') {
        return `Deleting from Internxt Drive`
      } else if (item.action === 'DELETED' && item.kind === 'LOCAL') {
        return `Deleted from your computer`
      } else if (item.action === 'DELETED' && item.kind === 'REMOTE') {
        return `Deleted from Internxt Drive`
      } else if (item.action === 'DELETE_ERROR') {
        return shortMessages[item.errorName]
      } else if (item.action === 'METADATA_READ_ERROR') {
        return shortMessages[item.errorName]
      } else {
        return ''
      }
    },
    getOperation(item) {
      if (
        item.action === 'DELETE' ||
        item.action === 'DELETED' ||
        item.action === 'DELETE_ERROR'
      ) {
        return 'delete'
      } else if (
        item.action === 'PULL' ||
        item.action === 'PULLED' ||
        item.action === 'PULL_ERROR'
      ) {
        if (item.kind === 'LOCAL') {
          return 'download'
        } else {
          return 'upload'
        }
      } else {
        return ''
      }
    },
    openSyncIssuesWindow() {
      ipcRenderer.send('open-sync-issues-window')
    },
    isAnError(item) {
      return ['PULL_ERROR', 'DELETE_ERROR', 'METADATA_READ_ERROR'].includes(
        item.action
      )
    }
  },
  filters: {
    showOnlyFilename(name) {
      return path.parse(name).base
    }
  }
}
</script>

// src/renderer/pages/Widget/SyncInfo.tsx
import { ReactNode, useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { SyncInfoUpdatePayload } from '../../../workers/sync';
import FileIcon from '../../assets/file.svg';
import FileWithOperation, {
  Operation,
} from '../../components/FileWithOperation';
import useSyncStatus from '../../hooks/SyncStatus';
import { shortMessages } from '../../messages/sync-error';
import { getBaseName } from '../../utils/path';
import useSyncStopped from '../../hooks/SyncStopped';
import { ProcessErrorName } from '../../../workers/types';
import { SyncStatus } from '../../../main/background-processes/sync';

export default function SyncInfo() {
  const [items, setItems] = useState<SyncInfoUpdatePayload[]>([]);

  const [syncStopped] = useSyncStopped();

  useEffect(() => {
    const removeListener = window.electron.onSyncInfoUpdate(onSyncItem);
    return removeListener;
  }, []);

  function onSyncStatusChanged(value: SyncStatus) {
    if (value === 'RUNNING') clearItems();
  }

  useSyncStatus(onSyncStatusChanged);

  function onSyncItem(item: SyncInfoUpdatePayload) {
    const MAX_ITEMS = 50;

    setItems((currentItems) => {
      const itemsWithoutGivenItem = currentItems.filter(
        (i) => i.name !== item.name
      );

      const itemIsAnError = [
        'PULL_ERROR',
        'RENAME_ERROR',
        'DELETE_ERROR',
        'METADATA_READ_ERROR',
      ].includes(item.action);

      const newItems = itemIsAnError
        ? itemsWithoutGivenItem
        : [item, ...itemsWithoutGivenItem].slice(0, MAX_ITEMS);

      return newItems;
    });
  }

  function clearItems() {
    setItems([]);
  }

  function removeOnProgressItems() {
    setItems((currentItems) => {
      return currentItems.filter(
        (item) =>
          item.action !== 'DELETE' &&
          item.action !== 'PULL' &&
          item.action !== 'RENAME'
      );
    });
  }

  useEffect(() => {
    if (syncStopped) removeOnProgressItems();
  }, [syncStopped]);

  return (
    <div className="relative min-h-0 flex-grow border-t border-t-l-neutral-30 bg-l-neutral-10 px-3">
      <div className="absolute top-0 left-0 flex w-full justify-end p-1">
        <div className="rounded bg-l-neutral-10 px-2">
          <button
            tabIndex={0}
            type="button"
            className={`select-none text-xs font-medium text-blue-60 hover:text-blue-70 active:text-blue-80 ${
              items.length === 0 ? 'opacity-0' : ''
            }`}
            onClick={clearItems}
            disabled={items.length === 0}
          >
            Clear
          </button>
        </div>
      </div>

      {items.length === 0 && <Empty />}
      <div className="scroll no-scrollbar h-full overflow-y-auto">
        <AnimatePresence>
          {items.map((item, i) => (
            <AnimationWrapper key={item.name} i={i}>
              <Item {...item} />
            </AnimationWrapper>
          ))}
        </AnimatePresence>
      </div>
    </div>
  );
}

function AnimationWrapper({
  children,
  key,
  i,
}: {
  children: ReactNode;
  key: string;
  i: number;
}) {
  return (
    <motion.div
      key={key}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0, transition: { delay: i * 0.03 } }}
      transition={{ duration: 0.25, ease: 'easeInOut' }}
    >
      {children}
    </motion.div>
  );
}

function Item({
  name,
  action,
  kind,
  progress,
  errorName,
}: SyncInfoUpdatePayload & {
  progress?: number;
  errorName?: ProcessErrorName;
}) {
  const progressDisplay =
    progress !== undefined ? `${(progress * 100).toFixed(0)}%` : '';

  let operation: Operation | undefined;
  if (action === 'DELETE' || action === 'DELETED' || action === 'DELETE_ERROR')
    operation = 'delete';
  else if (action === 'PULL' || action === 'PULLED' || action === 'PULL_ERROR')
    operation = kind === 'LOCAL' ? 'download' : 'upload';

  let description = '';

  if (action === 'PULL' && kind === 'LOCAL') description = 'Downloading';
  else if (action === 'PULL' && kind === 'REMOTE') description = 'Uploading';
  else if (action === 'PULLED' && kind === 'LOCAL') description = 'Downloaded';
  else if (action === 'PULLED' && kind === 'REMOTE') description = 'Uploaded';
  else if (action === 'DELETE' && kind === 'LOCAL')
    description = 'Deleting from your computer';
  else if (action === 'DELETE' && kind === 'REMOTE')
    description = 'Deleting from Internxt Drive';
  else if (action === 'DELETED' && kind === 'LOCAL')
    description = 'Deleted from your computer';
  else if (action === 'DELETED' && kind === 'REMOTE')
    description = 'Deleted from Internxt Drive';
  else if (errorName) description = shortMessages[errorName];

  const displayName = getBaseName(name);

  return (
    <div className="my-4 flex h-10 w-full select-none items-center overflow-hidden">
      <FileWithOperation
        operation={operation}
        className="flex-shrink-0"
        width={24}
      />
      <div className="ml-4 overflow-hidden">
        <h2 className="truncate text-sm font-medium text-neutral-700">
          {displayName}
        </h2>
        <p className="text-xs text-neutral-500">
          {description}
          <span>&nbsp;{progressDisplay}</span>
        </p>
      </div>
    </div>
  );
}

function Empty() {
  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1, transition: { delay: 0.4 } }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.5, ease: 'easeInOut' }}
      >
        <div className="trasform absolute left-1/2 top-1/2 w-full -translate-x-1/2 -translate-y-1/2 select-none text-center">
          <div className="relative h-16">
            <div className="absolute left-1/2 -translate-x-6 rotate-12 transform opacity-60">
              <FileIcon className="h-16 w-16" />
            </div>
            <div className="absolute left-1/2 -translate-x-10 -rotate-12 transform">
              <FileIcon className="h-16 w-16" />
            </div>
          </div>
          <p className="mt-7 text-sm text-blue-100">
            There is no recent activity
          </p>
          <p className="mt-1 px-4 text-xs text-m-neutral-100">
            Information will show up here when changes are made to sync your
            local folder with Internxt Drive
          </p>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
