// src/renderer/components/OnBoarding/OnBoarding.vue
<template>
  <div class="window flex flex-row w-full h-full text-neutral-500">

    <div class="relative flex flex-row w-full h-full p-8">

      <div class="relative flex flex-col h-full flex-grow -ml-8 pointer-events-none">
        <transition
          enter-active-class="transition-opacity duration-250"
          enter-class="opacity-0"
          enter-to-class="opacity-100"
          leave-active-class="transition-opacity duration-250 delay-500"
          leave-class="opacity-100"
          leave-to-class="opacity-0"
        >
          <img v-if="(slide === 0) && (getOS() === 'mac')" key="image-0" class="absolute object-right object-cover h-full" src="../../assets/images/onboarding/mac.png" />
          <img v-if="(slide === 0) && (getOS() === 'windows')" key="image-0" class="absolute object-right object-cover h-full" src="../../assets/images/onboarding/mac.png" />
          <img v-if="(slide === 1) && (getOS() === 'mac')" key="image-1" class="absolute object-right object-cover h-full" src="../../assets/images/onboarding/mac-finder-widget.png" />
          <img v-if="(slide === 1) && (getOS() === 'windows')" key="image-1" class="absolute object-right object-cover h-full" src="../../assets/images/onboarding/mac-finder-widget.png" />
        </transition>
      </div>

      <div v-if="slide === 0" key="slide-0" class="flex flex-col flex-shrink-0 items-center justify-center w-96 h-full space-y-6">

        <div class="flex flex-col items-center space-y-3">
          <img src="../../assets/images/onboarding/logo.svg" />
        
          <div class="flex flex-col items-center max-w-full">
            <h3 class="text-2xl font-semibold tracking-wide text-neutral-900 text-center">Welcome to Internxt, {{this.userName}}!</h3>
            <p>Let’s get everything on point together.</p>
          </div>
        </div>

        <button
          @click="nextSlide()"
          class="flex flex-row px-3 py-1 text-base bg-white rounded-lg border border-gray-100 shadow-sm"
        >
          Get started
        </button>
      </div>

      <div v-if="slide === 1" key="slide-1" class="flex flex-col flex-shrink-0 items-center justify-center w-96 h-full space-y-6">

        <div class="flex flex-col items-center space-y-6">
          <div class="flex flex-col items-center">
            <img src="../../assets/images/onboarding/folder.svg" />
            <p class="font-medium text-neutral-900">Internxt</p>
          </div>
        
          <div class="relative w-full">
            Internxt is a folder on your computer. It works<br />
            like your Documents or Photos folder. The files<br />
            you put in there are automatically synced for<br />
            you on <a class="text-blue-600 cursor-pointer" @click="openDriveInWebBrowser()">drive.internxt.com</a>.
          </div>
        </div>

        <button
          @click="prevSlide()"
          class="flex flex-row px-3 py-1 text-base bg-white rounded-lg border border-gray-100 shadow-sm"
        >
          Finish
        </button>
      </div>

    </div>

  </div>
</template>

<script>
import database from '../../../database'
const remote = require('@electron/remote')

export default {
  data() {
    return {
      slide: 0,
      forward: true,
      userName: null
    }
  },
  beforeCreate() {
    // remote.getCurrentWindow().center()
    remote.app.emit('enter-onboarding', true)
    remote.app.emit('window-show')

    database
      .Get('xUser')
      .then((xUser) => {
        this.userName = xUser.user.name
      })
      .catch((err) => {
        console.log('[Onboarding] Cannot get user name: ', err.message)
      })
  },
  methods: {
    getOS() {
      const platform = window.navigator.platform
      const macosPlatforms = ['Macintosh', 'MacIntel', 'MacPPC', 'Mac68K']
      const windowsPlatforms = ['Win32', 'Win64', 'Windows', 'WinCE']

      if (macosPlatforms.indexOf(platform) !== -1) {
        return 'mac'
      } else if (windowsPlatforms.indexOf(platform) !== -1) {
        return 'windows'
      } else if (/Linux/.test(platform)) {
        return 'linux'
      }
      return null
    },
    nextSlide() {
      this.slide = this.slide + 1
      this.forward = true
    },
    prevSlide() {
      if (this.slide > 0) this.slide = this.slide - 1
      this.forward = false
    },
    finishOnboarding() {
      remote.app.emit('window-pushed-to', '/xcloud')
      this.$router.push('/xcloud').catch(() => {})
      // remote.app.emit('enter-onboarding', false)
    },
    openDriveInWebBrowser() {
      remote.shell.openExternal('https://drive.internxt.com/app')
    }
  }
}
</script>

// src/renderer/pages/Onboarding/index.tsx
import { useState } from 'react';
import { Transition } from '@headlessui/react';
import { useTranslationContext } from 'renderer/context/LocalContext';
import Button from '../../components/Button';
import widgedWidget from '../../assets/onboarding/widget.png';
import macFinderWidgetAsset from '../../assets/onboarding/mac-finder-widget.png';
import Logo from '../../assets/onboarding/logo.svg';

function SideImageAnimation({
  display,
  children,
}: {
  display: boolean;
  children: JSX.Element;
}) {
  return (
    <Transition
      enter="transition-all duration-500 delay-0"
      enterFrom="opacity-0"
      enterTo="opacity-100"
      leave="transition-all ease-out duration-500 delay-0"
      leaveFrom="opacity-100"
      leaveTo="opacity-0"
      show={display}
      appear={display}
    >
      {children}
    </Transition>
  );
}

function SideTextAnimation({
  display,
  children,
}: {
  display: boolean;
  children: JSX.Element;
}): JSX.Element {
  return (
    <Transition
      enter="transition-all duration-200 delay-300"
      enterFrom="transform -translate-y-1.5 opacity-0"
      enterTo="transform translate-y-0 opacity-100"
      leave="transition-all ease-out duration-300"
      leaveFrom="transform translate-y-0 opacity-100"
      leaveTo="transform translate-y-2 opacity-0"
      show={display}
      appear={display}
    >
      {children}
    </Transition>
  );
}

export default function Onboarding() {
  const { translate, language } = useTranslationContext();
  const [slide, setSlide] = useState<number>(0);

  const nextSlide = () => {
    setSlide(slide + 1);
  };

  const finish = () => {
    window.electron.finishOnboarding();
  };

  return (
    <div className="draggable flex h-screen w-full bg-l-neutral-10 px-8 py-12 text-neutral-500">
      <div className="non-draggable pointer-events-none relative -mb-12 -ml-8 flex h-full flex-grow flex-col transition-all delay-100 duration-500 ease-in-out">
        <SideImageAnimation display={slide === 1}>
          <img
            key="image-1"
            className="absolute h-full object-cover object-right"
            src={macFinderWidgetAsset}
            alt="screenshot of the app widget on a mac"
          />
        </SideImageAnimation>
        <SideImageAnimation display={slide === 2}>
          <img
            key="image-2"
            className="absolute h-full origin-top-right object-cover object-right"
            style={{ transform: 'scale(1.14)' }}
            src={widgedWidget}
            alt="screenshot of the app widget on a mac"
          />
        </SideImageAnimation>
      </div>

      <div
        className={`${
          slide === 0 ? 'w-full' : 'w-96'
        } transition-all delay-100 duration-500 ease-in-out`}
      >
        {slide === 0 && (
          <div className="flex h-full grow flex-col items-center justify-center space-y-6 text-center">
            <Logo />
            <div>
              <h3 className="mb-2 text-2xl font-semibold tracking-wide text-neutral-900">
                {translate('onboarding.slides.welcome.title')}
              </h3>
              <p>{translate('onboarding.slides.welcome.description')}</p>
              <p>{translate('onboarding.slides.welcome.invitation')}</p>
            </div>

            <Button
              className="non-draggable"
              variant="default"
              onClick={() => nextSlide()}
            >
              {translate('onboarding.slides.welcome.next-slide')}
            </Button>
          </div>
        )}
        <SideTextAnimation display={slide === 1}>
          <div
            key="slide-1"
            className={`flex h-full w-96 flex-shrink-0 flex-col items-center justify-between space-y-6 ${
              language === 'en' ? 'py-8' : 'pb-8'
            }`}
          >
            <div className="flex flex-col items-center space-y-6">
              <h3 className="w-full text-left text-2xl font-semibold tracking-wide text-neutral-900">
                {translate('onboarding.slides.sync-folder.title')}
              </h3>

              <ul className="items-left relative flex w-full max-w-xs list-disc flex-col space-y-3 pl-4 text-base text-neutral-500">
                <li>
                  {translate('onboarding.slides.sync-folder.description-1')}
                </li>

                <li>
                  {translate('onboarding.slides.sync-folder.description-2')}
                </li>

                <li>
                  {translate('onboarding.slides.sync-folder.description-3')}
                </li>

                <li>
                  {translate('onboarding.slides.sync-folder.description-4')}
                </li>
              </ul>
            </div>

            <Button
              className="non-draggable"
              variant="default"
              onClick={() => nextSlide()}
            >
              {translate('onboarding.slides.sync-folder.next-slide')}
            </Button>
          </div>
        </SideTextAnimation>
        <SideTextAnimation display={slide === 2}>
          <div
            key="slide-2"
            className={`flex h-full w-96 flex-shrink-0 flex-col items-center justify-between space-y-6 ${
              language === 'en' ? 'py-8' : 'pb-8'
            }`}
          >
            <div className="flex flex-col items-center space-y-6">
              <h3 className="w-full text-left text-2xl font-semibold tracking-wide text-neutral-900">
                {translate('onboarding.slides.widget.title')}
              </h3>

              <ul className="items-left relative flex w-full max-w-xs list-disc flex-col space-y-3 pl-4 text-base text-neutral-500">
                <li>
                  {translate('onboarding.slides.widget.description-1')}
                  <a
                    className="text-blue-600 cursor-pointer underline"
                    href="https://drive.internxt.com/app"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Drive Web
                  </a>
                  .
                </li>

                <li>{translate('onboarding.slides.widget.description-2')}</li>

                <li>{translate('onboarding.slides.widget.description-3')}</li>

                <li>{translate('onboarding.slides.widget.description-4')}</li>

                <li>{translate('onboarding.slides.widget.description-5')}</li>
              </ul>
            </div>

            <Button
              className="non-draggable"
              variant="default"
              onClick={() => finish()}
            >
              {translate('onboarding.slides.widget.next-slide')}
            </Button>
          </div>
        </SideTextAnimation>
      </div>
    </div>
  );
}
